const express = require('express')
const cors = require('cors')
const multer = require('multer')
const { createTodo, getTodos, deleteTodo, updateTodo } = require('./controllers/todoController')
const dbConnect = require('./config/dbConfig')
const upload = require('./utils/upload')
const app = express()
app.use(express.json())
app.use(cors())
app.use('/upload', express.static('uploads'))
dbConnect()

app.get('/', (req, res) => { res.send('Hello world') })
app.post('/todo/create', upload.single('image'), createTodo)
app.get('/todo', getTodos)
app.delete('/todo/delete/:id', deleteTodo)
app.post('/todo/update/:id', updateTodo)
app.listen(5000, () => { console.log('Server is running') })